###### To solve a puzzle, you are given an initial state and a goal state.
###### Target is to reach goal state from initial state using puzzle rules.
######  We can move blank tile only on left, right, up, and down
![Capture.JPG](attachment:Capture.JPG)

# Generate an intial state of NPuzzle

In [1]:
import numpy as np
import random
def get_state(N):    
    state = [item for item in range(N*N)]# [0,1,2,...,15]
    #print(state)
    random.shuffle(state)
    #print(state)
    tmp = np.array(state)
    print(tmp.reshape(N,N))
    return state

In [4]:
get_state(3)

[[8 1 7]
 [0 5 2]
 [6 3 4]]


[8, 1, 7, 0, 5, 2, 6, 3, 4]

# Calculate inversion

Inversion is a pair of tiles that are in the reverse order from where they ought to be. In our case, the bigger number is in front of the smaller one.



![Capture.JPG](attachment:Capture.JPG)

In [5]:
def count_inversion(state):
    #arr = [i for i in arr if i !=0]
    print(state)
    inversion = []
    for i in range(len(state)):    
        count = 0
        for j in range(i+1,len(state)):        
            if state[i] > state[j]: 
                count = count + 1
        inversion.append(count)
    #print(inversion)
    return sum(inversion)

In [6]:
s = get_state(4)
count_inversion(s)

[[13  3  5 11]
 [ 0 10  1  6]
 [ 2 12  9 14]
 [15  4  7  8]]
[13, 3, 5, 11, 0, 10, 1, 6, 2, 12, 9, 14, 15, 4, 7, 8]


51

# **Find blank row**

In [ ]:
# find row position of the blank tile
def get_blank_row(state):
  # define here


# Solvability Rules

In [2]:

class Node:
    def __init__(self,data,level,fval):
       
        self.data = data
        self.level = level
        self.fval = fval
def generate_child(self):
     
        x,y = self.find(self.data,'_')
       
        val_list = [[x,y-1],[x,y+1],[x-1,y],[x+1,y]]
        children = []
        for i in val_list:
            child = self.shuffle(self.data,x,y,i[0],i[1])
            if child is not None:
                child_node = Node(child,self.level+1,0)
                children.append(child_node)
        return children
        
    def shuffle(self,puz,x1,y1,x2,y2):
    
        if x2 >= 0 and x2 < len(self.data) and y2 >= 0 and y2 < len(self.data):
            temp_puz = []
            temp_puz = self.copy(puz)
            temp = temp_puz[x2][y2]
            temp_puz[x2][y2] = temp_puz[x1][y1]
            temp_puz[x1][y1] = temp
            return temp_puz
        else:
            return None
def copy(self,root):
     
        temp = []
        for i in root:
            t = []
            for j in i:
                t.append(j)
            temp.append(t)
        return temp    
            
    def find(self,puz,x):
    
        for i in range(0,len(self.data)):
            for j in range(0,len(self.data)):
                if puz[i][j] == x:
                    return i,j
class Puzzle:
    def __init__(self,size):
       
        self.n = size
        self.open = []
        self.closed = []
def accept(self):
      
        puz = []
        for i in range(0,self.n):
            temp = input().split(" ")
            puz.append(temp)
        return puz
def f(self,start,goal):
     
        return self.h(start.data,goal)+start.level
def h(self,start,goal):
      
        temp = 0
        for i in range(0,self.n):
            for j in range(0,self.n):
                if start[i][j] != goal[i][j] and start[i][j] != '_':
                    temp += 1
        return temp
def process(self):
      
        print("Enter the start state matrix \n")
        start = self.accept()
        print("Enter the goal state matrix \n")        
        goal = self.accept()
start = Node(start,0,0)
        start.fval = self.f(start,goal)
       
        self.open.append(start)
        print("\n\n")
        while True:
            cur = self.open[0]
            print("")
            print("  | ")
            print("  | ")
            print(" \\\'/ \n")
            for i in cur.data:
                for j in i:
                    print(j,end=" ")
                print("")
         
            if(self.h(cur.data,goal) == 0):
                break
            for i in cur.generate_child():
                i.fval = self.f(i,goal)
                self.open.append(i)
            self.closed.append(cur)
            del self.open[0]

            self.open.sort(key = lambda x:x.fval,reverse=False)
puz = Puzzle(3)
puz.process()

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 20)